# Site settings
title: KJ6DXJ
description: > # this means to ignore newlines until "baseurl:"
  A simple blog.
#baseurl: "/drunken-avenger/" # the subpath of your site, e.g. /blog/
url: "http://www.kj6dxj.net" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
pygments: true

