# Site settings
title: KJ6DXJ
description: > # this means to ignore newlines until "baseurl:"
  A test site evaluating GitHub Pages and Jekyll.
baseurl: "/drunken-avenger" # the subpath of your site, e.g. /blog/
url: "http://EmpNorton.github.io" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
pygments: true

